### ISSUE TITLE
Add Datamanagement Workflow

### ISSUE THREAD

**Issue by TheNewCivilian** [TheNewCivilian/OpenLinePlanner#6]
Currently the data layer needs to be prepared upfront by the user.
To let more people use the tool, a simpler option to add new data to the tool is needed.
The following steps need to be done by the **user**:

1. Tell the system which area should be added
2. Input the inhabitants (commuters)

The **system** needs to fetch:

1. A .pbf containing the street network (maybe building data)
2.  A generated .geojson containing the population count in the area (currently using [OpenPopulationEstimator](https://github.com/TheNewCivilian/OpenPopulationEstimator))

Interface Spec:

Layer
* bounding box
* [centroid]

PUT /layer/ Add custom layer -> {bbox, [centroids]}
POST /layer/calculate Calculate layer with bounding box -> {osm_id}

GET /osm/admin_bounds/{lat}/{lon} -> [{osm_id,geojson}]
 v 
GET /layer/types -> [{type_name, description, [{question_name,question,datatype}]}]
 v
POST /layer/calculate {area_choice,type,answers}

GET /layer/{layer_id} Get single layer
GET /layer Get all layers
GET /layer/by_type/{type} Get merged layer by type
type: 
 * residents
 * workplaces
 * shopping

 user clicks map -> GET admin_bounds -> user chooses area -> type_modal -> user chooses type -> question_modal -> user answers questions -> POST /layer/calculate

**Comment by TheNewCivilian** [comment]
Some refinement of this issue is needed, as it might be beneficial to be able to load custom data into the tool and adjust optimization algorithms and display options.

**Comment by TheNewCivilian** [comment]
![Frame](https://user-images.githubusercontent.com/24456478/224065972-c6ee172a-704c-4bfc-a769-7c1e4b4e9602.png)
![Frame-1](https://user-images.githubusercontent.com/24456478/224065964-a8e73a89-3dab-4189-8d7c-61ee28f06653.png)
![Frame-2](https://user-images.githubusercontent.com/24456478/224065960-8ede0627-3a0e-402b-b3a7-631bf3459a38.png)
![Frame-3](https://user-images.githubusercontent.com/24456478/224065955-0dbac6c5-930d-4366-a0a8-3e79c0ee6550.png)

**Comment by zandemax** [comment]
Open TODOs:

- [x] Create endpoint to query overpass api and return resulting boundaries
- [x] Parse response from overpass api
- [x] Return parsed response for frontend
- [x] Create endpoint to get pbf from protomaps
- [ ] Forward pbf to openhousepopulator and save the result as a layer
